baseURL: 'https://chase-mortensen.github.io/heqHomeLoans/'
languageCode: en-us
defaultContentLanguage: en
title: H*eq*
theme: hermit
publishDir: docs
pygmentsCodefences: true
pygmentsUseClasses: true
rssLimit: 10
copyright: ''
enableEmoji: true
author:
  name: HEQ LLC nmls 2002811
blackfriday: {}
taxonomies:
  tag: tags
params:
  dateform: 'Jan 2, 2006'
  dateformShort: Jan 2
  dateformNum: '2006-01-02'
  dateformNumTime: '2006-01-02 15:04 -0700'
  themeColor: '#494f5c'
  homeSubtitle: Home Loans
  footerCopyright: ' &#183; <a href="" target="_blank" rel="noopener">CC</a>'
  justifyContent: false
  relatedPosts: false
  code_copy_button: true
  social:
    - name: email
      url: >-
        https://blinksmartform.mortgage/form/uwm-leads-loanOfficerID=T22GAJ82&broker=Q9F38CY9
menu:
  main:
    - name: Enter
      url: about-heq/
      weight: 20

